<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/en/organisations/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/organisations/index.php",
	),
	array(
		"CONDITION" => "#^/en/all-authors/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/all-authors/index.php",
	),
	array(
		"CONDITION" => "#^/organisations/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/organisations/index.php",
	),
	array(
		"CONDITION" => "#^/en/chapters/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/chapters/index.php",
	),
	array(
		"CONDITION" => "#^/all-authors/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/all-authors/index.php",
	),
	array(
		"CONDITION" => "#^/en/personal/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/en/personal/index.php",
	),
	array(
		"CONDITION" => "#^/en/section/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/section/index.php",
	),
	array(
		"CONDITION" => "#^/en/faculty/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/faculty/index.php",
	),
	array(
		"CONDITION" => "#^/en/rubrics/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/papers/rubrics/index.php",
	),
	array(
		"CONDITION" => "#^/en/journal/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/journal/index.php",
	),
	array(
		"CONDITION" => "#^/en/lecture/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/lecture/index.php",
	),
	array(
		"CONDITION" => "#^/en/papers/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/papers/index.php",
	),
	array(
		"CONDITION" => "#^/en/themes/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/themes/index.php",
	),
	array(
		"CONDITION" => "#^/chapters/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/chapters/index.php",
	),
	array(
		"CONDITION" => "#^/en/books/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/books/index.php",
	),
	array(
		"CONDITION" => "#^/en/blogs/#",
		"RULE" => "",
		"ID" => "bitrix:blog",
		"PATH" => "/en/blogs/index.php",
	),
	array(
		"CONDITION" => "#^/personal/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/personal/index.php",
	),
	array(
		"CONDITION" => "#^/section/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/section/index.php",
	),
	array(
		"CONDITION" => "#^/lecture/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/lecture/index.php",
	),
	array(
		"CONDITION" => "#^/faculty/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/faculty/index.php",
	),
	array(
		"CONDITION" => "#^/journal/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/journal/index.php",
	),
	array(
		"CONDITION" => "#^/en/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/news/index.php",
	),
	array(
		"CONDITION" => "#^/rubrics/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/papers/rubrics/index.php",
	),
	array(
		"CONDITION" => "#^/papers/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/papers/index.php",
	),
	array(
		"CONDITION" => "#^/themes/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/themes/index.php",
	),
	array(
		"CONDITION" => "#^/books/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/books/index.php",
	),
	array(
		"CONDITION" => "#^/blogs/#",
		"RULE" => "",
		"ID" => "bitrix:blog",
		"PATH" => "/blogs/index.php",
	),
	array(
		"CONDITION" => "#^/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
	),
);

?>